### ISSUE TITLE
Change in OxmlElement reference from docx

### ISSUE THREAD

**Issue by iguy0** [fbarre96/MarkDownToDocxStyle#1]
Hello,

Great library! There was a recent change in how OxmlElement is imported. According to https://github.com/python-openxml/python-docx/issues/1256, the file markdowntodocx\markdownconverter.py line 11 should be "from docx.oxml.parser import OxmlElement"

Changing this has worked for me.

Best Regards

**Comment by fbarre96** [comment]
Hello,
Thanks ! Yes I bumped into this issue earlier and just fixed the version of python-docx to 0.8.11 where it worked.
In the latest release I did just now (v 0.1.5.0) I updated the python-docx library to its latest version and fixed the breaking changes.
So please upgrade to try it.

Regards

**Comment by iguy0** [comment]
Awesome! Thank you. Yeah, i bumbed my version and it worked as well. Ty!!
