### ISSUE TITLE
Is there a function to convert Markdown text to Docx  ?

### ISSUE THREAD

**Issue by iguy0** [fbarre96/MarkDownToDocxStyle#2]
""""""from markdowntodocx.markdownconverter import convertMarkdownInFile
import io

markdown_text = """# H1 Header: Welcome to My Markdown Guide!

## H2 Header: Quick Overview
Markdown is a lightweight markup language that you can use to add formatting elements to plaintext text documents. Created by John Gruber in 2004, Markdown is now one of the world’s most popular markup languages.

#### H4 Header: Formatting Text
You can do numerous things with Markdown format, including:

- **Bold** text
- *Italic* text
- **_Combined emphasis_**

> **Note:** Markdown is not the same as Markup. They’re different, remember!

##### H5 Header: Unordered Lists
- Item one
- Item two
  - Sub Item one
  - Sub Item two

##### H5 Header: Ordered Lists
1. First item
2. Second item
    1. Subitem
    2. Subitem

#### H4 Header: Adding Links and Images

Here is a clickable link to [OpenAI](https://www.openai.com), the organization behind Assistant.

Here is an image:

![Alt text for image](https://via.placeholder.com/150)

#### H4 Header: Inserting Code

```python
# This is some Python code
def say_hello(name):
    print("Hello, " + name)
```

##### H5 Header: Inline Code
You can also use inline `code` within your text.

### H3 Header: Using Blockquotes

> Markdown uses email-style > characters for blockquoting.
> It’s very handy for email mimicking."""

last_message_inmemoryfile = io.StringIO(markdown_text)

filename = 'response.docx'

convertMarkdownInFile(last_message_inmemoryfile, filename)""""""

I'm receiving an error on the code above since the input is a markdown formatted string and not a word file with markdown in it. Is there an easy way to read the string and parse it into a formatted word doc?

Best Regards

**Comment by fbarre96** [comment]
Hello,

There are many ways to achieve what you want. I implemented a short function to do this in the latest version (0.1.5.0) so you can check how it works, but the downfall of this is will use the default world styles for markdown Code, Hyperlink, Headings/Headers  and the Bullet list will not have bullets (it is really had to do it in python-docx).

If you don't need pretty styling at generation use **markdownToWordFromString**:
```python
from markdowntodocxconverter import markdownToWordFromString
res, msg = markdownToWordFromString(your_markdown_string, outfile_path_to_create.docx)
```

If you need other styles or bullet list, you should at least create a blank document with desired styling created and use:
**convertMarkdownInFile**

If you need templating before styling, I recommand docxtpl.

Regards

**Comment by iguy0** [comment]
Your library is simple and elegant, I'm trying to avoid templating for now. It served the purpose for the example. Much appreciated, Thank you for sharing this!

**Comment by fbarre96** [comment]
Thank ! I'll close this issue then.
